namespace Firefly.Application.Quotations.Dtos
{
    public record DocumentEmailPreviewDto(
        int DocumentId,
        string DocumentNumber,
        List<string> ToRecipients,
        string DefaultSubject,
        string AutoGeneratedBody,
        string CustomerName,
        string ContactName,
        decimal TotalAmount
    );

    public record SendEmailRequestDto(
        List<string> RecipientEmails,
        string Subject,
        string Body
    );
}